/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.item;

import dao.InvoiceDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import model.Invoice;
import model.InvoiceItem;
import model.ItemStats;
import model.User;
import view.user.ManagerHomeFrm;

/**
 *
 * @author HLC_2021
 */
public class InvoiceFrm extends javax.swing.JFrame implements ActionListener {
    private User u;
    private ItemStats is;
    /**
     * Creates new form InvoiceFrm
     * @param u
     * @param is
     * @param sd
     * @param ed
     */
    public InvoiceFrm(User u, ItemStats is, Date sd, Date ed) {
        this.u = u;
        this.is = is;
        initComponents();
        btnReturnToItemStatsView.addActionListener(this);
        btnReturnToHomeScreen.addActionListener(this);
        TableColumnModel columnModel = tblListInvoices.getColumnModel();
        columnModel.getColumn(4).setPreferredWidth(100);
        ArrayList<Invoice> resultList = new InvoiceDAO().getListInvoices(is.getId(), sd, ed);
        DefaultTableModel model = (DefaultTableModel)tblListInvoices.getModel();
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (Invoice i : resultList) {
            InvoiceItem ii = i.getInvoiceItem().get(0);
            model.addRow(new Object[]{
                i.getId(), i.getSubagence().getId(), i.getSubagenceName(), sdf.format(i.getDateIssued()), ii.getQuantity() * ii.getItemPrice(), ii.getQuantity()
            });
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnReturnToItemStatsView) {
            ItemStatsFrm itemStatsFrm = new ItemStatsFrm(u);
            itemStatsFrm.setLocation(this.getLocation());
            itemStatsFrm.setVisible(true);
            this.dispose();
        }
        else if (e.getSource() == btnReturnToHomeScreen) {
            ManagerHomeFrm managerHomeFrm = new ManagerHomeFrm(u);
            managerHomeFrm.setLocation(this.getLocation());
            managerHomeFrm.setVisible(true);
            this.dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItemInfo = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblItemDescription = new javax.swing.JLabel();
        lblQuantitySold = new javax.swing.JLabel();
        lblRevenue = new javax.swing.JLabel();
        btnReturnToItemStatsView = new javax.swing.JButton();
        btnReturnToHomeScreen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListInvoices = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblItemInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemInfo.setText("Item information:");

        lblItemCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemCode.setText("Code: " + is.getId());

        lblItemName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemName.setText("Name: " + is.getItemName());

        lblItemDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblItemDescription.setText("Description: " + is.getItemDescription());

        lblQuantitySold.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuantitySold.setText("Quantity sold: " + is.getTotalQuantitySold());

        lblRevenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRevenue.setText("Revenue (in million VND): " + is.getTotalRevenue());

        btnReturnToItemStatsView.setBackground(new java.awt.Color(193, 218, 243));
        btnReturnToItemStatsView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturnToItemStatsView.setText("Return");
        btnReturnToItemStatsView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnReturnToHomeScreen.setBackground(new java.awt.Color(193, 218, 243));
        btnReturnToHomeScreen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturnToHomeScreen.setText("Home");
        btnReturnToHomeScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblListInvoices.setBackground(new java.awt.Color(193, 218, 243));
        tblListInvoices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblListInvoices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice code", "Subagence code", "Subagence name", "Date issued", "Total price (million VND)", "Number of items"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListInvoices.setRowSelectionAllowed(false);
        tblListInvoices.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblListInvoices.setShowGrid(false);
        tblListInvoices.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblListInvoices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItemName)
                    .addComponent(lblItemCode)
                    .addComponent(lblItemDescription)
                    .addComponent(lblQuantitySold)
                    .addComponent(lblRevenue))
                .addGap(521, 521, 521))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblItemInfo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReturnToItemStatsView, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReturnToHomeScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblItemInfo)
                .addGap(18, 18, 18)
                .addComponent(lblItemCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantitySold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRevenue)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReturnToItemStatsView, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturnToHomeScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToHomeScreen;
    private javax.swing.JButton btnReturnToItemStatsView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemDescription;
    private javax.swing.JLabel lblItemInfo;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblQuantitySold;
    private javax.swing.JLabel lblRevenue;
    private javax.swing.JTable tblListInvoices;
    // End of variables declaration//GEN-END:variables

    
}
