/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.user;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author HLC_2021
 */
public class ManagerHomeFrm extends javax.swing.JFrame implements ActionListener {
    private User user;
    /**
     * Creates new form ManagerHomeFrm
     * @param user
     */
    public ManagerHomeFrm(User user) {
        this.user = user;
        initComponents();
        btnViewStats.addActionListener(this);
        btnLogout.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnViewStats) {
            StatsFrm statsFrm = new StatsFrm(user);
            statsFrm.setLocation(this.getLocation());
            statsFrm.setVisible(true);
            this.dispose();
        } else if (e.getSource() == btnLogout) {
            LoginFrm loginFrm = new LoginFrm();
            loginFrm.setLocation(this.getLocation());
            loginFrm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "This function is under construction!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManagerHome = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnViewStats = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblManagerHome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblManagerHome.setText("Manager Home");

        lblName.setText(user.getName());
        lblName.setToolTipText("");
        lblName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnViewStats.setBackground(new java.awt.Color(193, 218, 243));
        btnViewStats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewStats.setText("View Statistics");
        btnViewStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnLogout.setBackground(new java.awt.Color(193, 218, 243));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewStats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblName))
                            .addComponent(lblManagerHome))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblManagerHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName)
                .addGap(18, 18, 18)
                .addComponent(btnViewStats, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewStats;
    private javax.swing.JLabel lblManagerHome;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables

    
}
