/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.user;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.User;
import view.item.ItemStatsFrm;

/**
 *
 * @author HLC_2021
 */
public class StatsFrm extends javax.swing.JFrame implements ActionListener {
    private User user;
    /**
     * Creates new form StatsFrm
     * @param user
     */
    public StatsFrm(User user) {
        this.user = user;
        initComponents();
        btnViewItemStats.addActionListener(this);
        btnReturnToManagerHomeView.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnViewItemStats) {
            ItemStatsFrm itemStatsFrm = new ItemStatsFrm(user);
            itemStatsFrm.setLocation(this.getLocation());
            itemStatsFrm.setVisible(true);
            this.dispose();
        } else if (e.getSource() == btnReturnToManagerHomeView) {
            ManagerHomeFrm managerHomeFrm = new ManagerHomeFrm(user);
            managerHomeFrm.setLocation(this.getLocation());
            managerHomeFrm.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "This function is under construction!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatistic = new javax.swing.JLabel();
        btnViewItemStats = new javax.swing.JButton();
        btnReturnToManagerHomeView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStatistic.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStatistic.setText("Statistic");

        btnViewItemStats.setBackground(new java.awt.Color(193, 218, 243));
        btnViewItemStats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnViewItemStats.setText("Statistic of Item");
        btnViewItemStats.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnReturnToManagerHomeView.setBackground(new java.awt.Color(193, 218, 243));
        btnReturnToManagerHomeView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturnToManagerHomeView.setText("Return");
        btnReturnToManagerHomeView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnViewItemStats, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblStatistic))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnReturnToManagerHomeView, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblStatistic)
                .addGap(18, 18, 18)
                .addComponent(btnViewItemStats, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnReturnToManagerHomeView, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToManagerHomeView;
    private javax.swing.JButton btnViewItemStats;
    private javax.swing.JLabel lblStatistic;
    // End of variables declaration//GEN-END:variables

    
}
